#' Example Data Generated by the generate_data Function
#'
#' Generated by the generate_data function.
#'
#' @docType data
#' @usage data (example_data)
#' @format A linreg_data object.
#' @keywords datasets example example_data
#' @examples
#' data (example_data)
#' example_data$B
#' example_data$X
#' example_data$Y
